In [2]:
# import numpy
import numpy as np
# create array x

x = np.array([1,2,3,4])

In [6]:
# print the shape of x
print x
np.shape(x)

[1 2 3 4]


(4,)

In [4]:
# create a two dimensional array

y = np.array([[1,2],[3,4]])

In [7]:
# print shape of 2d array
print y
np.shape(y)

[[1 2]
 [3 4]]


(2, 2)

In [22]:
# reshape the array to 2 x 6
# z = np.array([[1,2,3,4],[3,4,4,4],[3,4,4,4]])
z = np.array([[1,2,3],[3,4,4],[3,4,4],[7,8,9]])
print z
print np.shape(z)
np.reshape(z,(2,6))

[[1 2 3]
 [3 4 4]
 [3 4 4]
 [7 8 9]]
(4, 3)


array([[1, 2, 3, 3, 4, 4],
       [3, 4, 4, 7, 8, 9]])

In [34]:
# reshape the array to 1 x 12
rs = np.reshape(z,(1,12))
rs

array([[1, 2, 3, 3, 4, 4, 3, 4, 4, 7, 8, 9]])

In [21]:
# transpose the array
np.transpose(z)

array([[1, 3, 3],
       [2, 4, 4],
       [3, 4, 4],
       [4, 4, 4]])

In [44]:
# indexing method 1
# find the 5th value 
# z[0][0]
print rs[0][4]
print y[0][1]

4
2


In [56]:
# indexing method 2
#2nd to last value
print rs[0][-2]
print z[3][-2]

8
8


In [66]:
# indexing method 3
#elements 2 to 5
for i in range(1,5):
    print rs[0][i]

arr = rs[0][1:5]
# arr2 = z[1][1:4]
print arr               

2
3
3
4
[2 3 3 4] [3 4 4]


In [81]:
# indexing method 4
# elements 1,2,3 and 6 -- using the index array
index = np.array([1,2,3,6])
print rs
print rs[0][index-1]


[[1 2 3 3 4 4 3 4 4 7 8 9]]
[1 2 3 4]


In [82]:
# indexing method 5
# values in array > 4
bool1 = z > 4
print bool1
print z[bool1]

bool2 = rs > 2

print bool2
print rs[bool2]

[[1 2 3]
 [3 4 4]
 [3 4 4]
 [7 8 9]]
[[False False False]
 [False False False]
 [False False False]
 [ True  True  True]]
[7 8 9]
[[False False  True  True  True  True  True  True  True  True  True  True]]
[3 3 4 4 3 4 4 7 8 9]


In [101]:
# 3 dimensional array
# abc = np.reshape(rs,(2,3,3))
abc = np.reshape(rs,(2,3,2))
abc

array([[[1, 2],
        [3, 3],
        [4, 4]],

       [[3, 4],
        [4, 7],
        [8, 9]]])

In [102]:
print len(abc)
print len(abc[0][0])


print abc[abc>3]

2
2
[4 4 4 4 7 8 9]


In [103]:
n = np.array([1,2,3,4,5,6,7,8,9,10])
print n

[ 1  2  3  4  5  6  7  8  9 10]


In [113]:
# 4 dimensional array

p = np.array(range(0,100)) 

arr4 = np.reshape(p, (2,5,2,5))
print arr4
print np.shape(arr4)
result =  list(arr4[1][3][1][2:5]) + list (arr4[1][4][0][0:2])
print result

[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]]

  [[10 11 12 13 14]
   [15 16 17 18 19]]

  [[20 21 22 23 24]
   [25 26 27 28 29]]

  [[30 31 32 33 34]
   [35 36 37 38 39]]

  [[40 41 42 43 44]
   [45 46 47 48 49]]]


 [[[50 51 52 53 54]
   [55 56 57 58 59]]

  [[60 61 62 63 64]
   [65 66 67 68 69]]

  [[70 71 72 73 74]
   [75 76 77 78 79]]

  [[80 81 82 83 84]
   [85 86 87 88 89]]

  [[90 91 92 93 94]
   [95 96 97 98 99]]]]
(2, 5, 2, 5)
[87, 88, 89, 90, 91]
